import {
  Heading,
  ListItem,
  OrderedList,
  Text,
  UnorderedList,
  Image,
  Link,
} from "@chakra-ui/react";
import { MyCodeBlock } from "./components/MyCodeBlock";

export const GITHUB_URL = "https://github.com/jacksonet00";
export const LINKEDIN_URL = "https://linkedin.com/in/jacksonet00";
export const SOURCE_CODE_URL =
  "https://github.com/jacksonet00/jacksontaylor.info";
export const HOME_PAGE_DATA = {
  greeting: {
    headline: "greetings",
    subText: `i'm jackson, a software developer.`,
  },
  aboutMe: {
    paragraphs: [
      `I’m a senior at the University of Florida 🐊 studying Computer Science with a minor in Math. During my first three years at UF, I've had the opportunity to participate in hackathons and build a variety of personal projects, serve as a Teaching Assistant, and intern full time as a Software Engineer in the SF Bay Area 🌁.`,
      `When I'm not coding or browsing Pinterest, I enjoy practicing yoga 🧘🏼‍♂️, running 🏃🏼‍♂️, and engaging with the community through volunteering and working at local coffee shops ☕️. I'm passionate about technology and excited by any opportunity to direct that passion towards making a positive impact in peoples' lives.`,
    ],
  },
  projects: [
    {
      title: "Sock: for shared spaces",
      link: "https://thesockapp.com",
      description: "A cross platform app which allows roommates to share status, check who is home, and receive updates automatically when returning home. Since launch in beta, it has received 250+ downloads and grown a small test group of 25 daily active users.",
      tags: ["Typescript", "React Native", "Google Cloud Platform"],
    },
    {
      title: "the not fat ppl",
      link: "https://github.com/jacksonet00/the-not-fat-ppl-leaderbaord",
      description: "An online leaderboard for workouts that is generated by feeding an iMessage group chat to a data processing pipeline which converts check mark emojis indicating workouts into a line chart with relevant statistics.",
      tags: ["Typescript", "Next JS", "React", "Google Cloud Platform"],
    },
    {
      title: "urLOL",
      link: "https://github.com/jacksonet00/bunnylol",
      description: "An open source clone of the popular tool \"bunnylol\" which enables shortcuts for visiting and searching websites directly in the browser's search bar.",
      tags: ["Python", "Docker", "Flask"]
    },
    {
      title: "Applied Data Science: Content Recommendation Systems",
      link: "https://medium.com/@jacksonet00/applied-data-science-content-recommendation-systems-6904ffafdf4",
      description: "An analysis of a variety of machine learning approaches relevant for content recommendation with sparse data.",
      tags: ["Content Filtering", "Collaborative Filtering", "Sparse NN"],
    },
  ],
  experiences: [
    {
      company: "Meta",
      role: "Software Engineer Intern",
      date: "May 2022 - August 2022",
      bullets: [ // todo: add bolding
        "Optimized a recommendation service for Facebook Messenger and Instagram Direct in C++ resulting in 15% lower CPU utilization and 10% higher throughput. The optimization process included techniques such as multi-threading, batching, and local caching.",
        `Enabled remote machine learning prediction for video autoplay recommendations by implementing a backend service to serve results from models too large to run with on device memory.`
      ],
      tags: ["Machine Learning", "C++", "React", "Javascript", "Python", "PHP"],
    },
    {
      company: "JP Morgan Chase",
      role: "Software Engineer Intern",
      date: "June 2021 - August 2021",
      bullets: [
        `Designed and implemented a full stack web application which improved the workflow of customer service representatives by providing access to internal data through an interactive interface.`,
        `Developed a Java API used by developers across multiple organizations that serves data previously only available through a COBOL terminal.`,
      ],
      tags: ["Fullstack Development", "Java",  "React", "Node", "Javascript"],
    },
  ],
  skills: [
    {
      type: "Application Development",
      items: [
        "Typescript",
        "React-Native",
        "React",
        "Node",
        "Docker",
        "Cloud Services",
      ],
    },
    {
      type: "Backend Development",
      items: ["Java", "Python", "C++", "SQL", "REST", "GraphQL"],
    },
    {
      type: "Data Analysis",
      items: [
        "Python",
        "Numpy",
        "Matplotlib",
        "Pandas",
        "Machine Learning",
        "Google Sheets",
      ],
    },
  ],
};

export const CHAKRA_UI_MARKDOWN_OPTIONS = {
  wrapper: "article",
  overrides: {
    h1: {
      component: Heading,
      props: {
        fontSize: "4xl",
        marginBottom: 6,
      },
    },
    h2: {
      component: Heading,
      props: {
        fontSize: "3xl",
        marginBottom: 6,
      },
    },
    h3: {
      component: Heading,
      props: {
        fontSize: "2xl",
        marginBottom: 6,
      },
    },
    h4: {
      component: Heading,
      props: {
        fontSize: "xl",
        marginBottom: 6,
      },
    },
    h5: {
      component: Heading,
      props: {
        fontSize: "lg",
        marginBottom: 6,
      },
    },
    h6: {
      component: Heading,
      props: {
        fontSize: "md",
        marginBottom: 6,
      },
    },
    p: {
      component: Text,
      props: {
        fontSize: "lg",
        marginBottom: 6,
      },
    },
    ul: {
      component: UnorderedList,
      props: {
        fontSize: "lg",
        marginBottom: 6,
      },
    },
    ol: {
      component: OrderedList,
      props: {
        fontSize: "lg",
        marginBottom: 6,
      },
    },
    li: {
      component: ListItem,
      props: {
        fontSize: "lg",
      },
    },
    code: {
      component: MyCodeBlock,
      props: {
        marginBottom: 6,
      },
    },
    img: {
      component: Image,
      props: {
        marginBottom: 6,
        marginTop: 6,
      },
    },
    a: {
      component: Link,
      props: {
        marginBottom: 6,
        textDecoration: "underline",
        isExternal: true,
      },
    },
  },
};
